document.lss_helper.vehicleResend = {
  'Löschfahrzeug (LF)': 'LF',
  'Löschfahrzeuge (LF)': 'LF',
  'Löschfahrzeug oder Rüstwagen': 'LF',
  'Rüstwagen oder HLF': 'RW',
  'Drehleiter (DLK 23)': 'DLK',
  'Drehleitern (DLK 23)': 'DLK',
  'FwK': 'FWK',
  'Schlauchwagen (GW-L2 Wasser oder SW)': 'SW',
  'ELW 1': 'ELW',
  'ELW 2': 'ELW2',
  'GW-Atemschutz': 'GWA',
  'GW-Gefahrgut': 'GWG',
  'GW-Höhenrettung': 'GWH',
  'GW-Messtechnik': 'GWM',
  'GW-Öl': 'GWO',
  'Dekon-P': 'DEKONP',

  'RTW oder KTW oder KTW-B': 'RTW',
  'GW-San': 'GWSAN',

  'FuStW': 'POL',
  'Funkstreifenwagen oder Polizeimotorrad': 'POL',
  'Funkstreifenwagen oder Polizeimotorräder': 'POL',
  'FüKW (Polizei)': 'FUEKW',
  'Zivilstreifenwagen': 'ZIV',
  'leBefKw': 'BEFKW',
  'GruKw': 'GRUKW',
  'SEK-Fahrzeuge': 'SEK',
  'MEK-Fahrzeuge': 'MEK',
  'Polizeihubschrauber': 'POLH',

  'Gerätekraftwagen (GKW)': 'GKW',
  'THW-Einsatzleitung (MTW TZ)': 'THWMTW',
  'MzGW (FGr N)': 'THWGWN',
  'MzGW SB': 'THWGWSB',
  'Radlader (BRmG R)': 'THWBRG',
  'LKW Kipper (LKW K 9)': 'THWLKWK9',
  'Rettungshundestaffel': 'DOG',
  'NEA50': 'AAOTHWNEA',

  'Betreuungs- und Verpflegungsausstattung': 'AAOSEGBT',
  'Boot': 'BOAT',
  'Drohneneinheit': 'DROHNE',
};