// document.lss_helper.vehicleResend['Tragehilfe (z.B. durch ein LF)'] = 'LF';
document.lss_helper.vehicleResend = {
  'Löschfahrzeug (LF)': 'LF',
  'Löschfahrzeuge (LF)': 'LF',
  'Löschfahrzeug oder Rüstwagen': 'LF',
  'Tragehilfe (z.B. durch ein LF)': 'LF',
  'Rüstwagen oder HLF': 'RW',
  'Drehleiter (DLK 23)': 'DLK',
  'Drehleitern (DLK 23)': 'DLK',
  'FwK': 'FWK',
  'Schlauchwagen (GW-L2 Wasser oder SW)': 'SW',
  'ELW 1': 'ELW',
  'ELW 2': 'ELW2',
  'GW-Atemschutz': 'GWA',
  'GW-Gefahrgut': 'GWG',
  'GW-Höhenrettung': 'GWH',
  'GW-Messtechnik': 'GWM',
  'GW-Öl': 'GWO',
  'Dekon-P': 'DEKONP',
  'Lüfter': 'LUEFTER',

  'Teleskopmast': 'TELE',
  'Turbolöscher': 'TURBO',
  'ULF mit Löscharm': 'ULF',

  'RTW': 'RTW',
  'RTW oder KTW oder KTW-B': 'RTWKTWKTWB',
  'RTW oder KTW-B': 'RTWKTWB',
  'GW-San': 'GWSAN',
  'ITW': 'ITW',

  'FuStW': 'POL',
  'FuStW (AP)': 'POLAP',
  'Funkstreifenwagen oder Polizeimotorrad': 'POL',
  'Funkstreifenwagen oder Polizeimotorräder': 'POL',
  'Funkstreifenwagen (Dienstgruppenleitung)': '103',
  'Polizeimotorräder': '95',
  'FüKW (Polizei)': 'FUEKW',
  'Zivilstreifenwagen': 'ZIV',
  'leBefKw': 'BEFKW',
  'GruKw': 'GRUKW',
  'SEK-Fahrzeuge': 'SEK',
  'MEK-Fahrzeuge': 'MEK',
  'DHuFüKW': '94',
  'Polizeihubschrauber': 'POLH',
  'Außenlastbehälter (allgemein)': '96',
  'LauKw': '165',

  'Gerätekraftwagen (GKW)': 'GKW',
  'THW-Einsatzleitung (MTW TZ)': 'THWMTW',
  'THW-Einsatzleitung (MTW-TZ)': 'THWMTW',
  'MzGW (FGr N)': 'THWGWN',
  'MzGW SB': 'THWGWSB',
  'LKW Kipper (LKW K 9)': 'THWBRG', // used to be 'THWLKWK9',
  // 'Radlader (BRmG R)': 'THWBRG', // cant be send alone
  'Rettungshundestaffel': 'DOGRESCUE',
  'Rettungshundestaffeln': 'DOGRESCUE',
  'NEA50': 'AAOFFNEA',
  'Anhänger Drucklufterzeugung': 'THWDLE',
  'Schmutzwasserpumpe': 'THWSWP',
  'Schmutzwasserpumpen': 'THWSWP',
  'GW-Taucher': '63',
  'FüKomKW': '146', //'145',
  // 'Anh FüLa': '146',
  'Mobilkran': '182',
  'Mobilkräne': '182',
  'Anh Plattform (FGr BrB)': '183',

  'MTW-TeSi': '173',
  'GW-TeSi': '174',
  // 'Anh TeSi': '174',

  'Betreuungs- und Verpflegungsausstattung': 'AAOSEGBT',
  'Betreuungs- und Verpflegungsausstattungen': 'AAOSEGBT',
  'Boot': 'BOAT',
  'Boote': 'BOAT',
  'Drohneneinheit': 'DROHNE',
};
